In [1]:
from google.colab import files
files.upload()

Saving pandas_new.xlsx to pandas_new.xlsx

{'pandas_new.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00b\xee\x9dh^\x01\x00\x00\x90\x04\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x94\xcbN\xc30\x10E\xf7H\xfcC\xe4-J\xdc\xb2@\x085\xed\x82\xc7\x12*Q>\xc0\xc4\x93\xc6\xaac[\x9eii\xff\x9e\x89\xfb\x10B\xa1\x15j7\xb1\x12\xcf\xdc{2\xf1\xcdh\xb2nm\xb6\x82\x88\xc6\xbbR\x0c\x8b\x81\xc8\xc0U^\x1b7/\xc5\xc7\xec%\xbf\x17\x19\x92rZY\xef\xa0\x14\x1b@1\x19__\x8df\x9b\x00\x98q\xb7\xc3R4D\xe1AJ\xac\x1ah\x15\x16>\x80\xe3\x9d\xda\xc7V\x11\xdf\xc6\xb9\x0c\xaaZ\xa89\xc8\xdb\xc1\xe0NV\xde\x118\xca\xa9\xd3\x10\xe3\xd1\x13\xd4ji){^\xf3\xe3-I\x04\x8b"{\xdc\x16v^\xa5P!XS)bR\xb9r\xfa\x97K\xbes(\xb83\xd5`c\x02\xde0\x86\x90\xbd\x0e\xdd\xce\xdf\x06\xbb\xbe7\x1eM4\x1a\xb2\xa9\x8a\xf4\xaaZ\xc6\x90k+\xbf|\\|z\xbf(\x8e\x8b\xf4P\xfa\xba6\x15h_-[\x9e@\x81!\x82\xd2\xd8\x00Pk\x8b\xb4\x16\xad2n\xcf}\xc4?\x15\xa3L\xcb\xf0\xc2 \xdd\xfb%\xe1\x13\x1c\xc4\xdf\x1bd\xba\x9e\x8f\x90dN\x18"m,\xe0\xa5\xc7\x9eDO97*\x82~\xa7\xc8\xc9\xb88\xc0O\xedc\x1c|n\xa6\xd1\x07\xe4\x04E\xf8\xff\x14\xf6\x11\xe9\xba\xf3\xc0B\x10\xc9\xc0!$}\x87\xed\xe0\xc8\xe9;{\xec\xd0\xe5[\x83\xee\xf1\x96\xe9\x7f2\xfe\x06\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xb5U0#\xf4\x00\x00\x00L\x02\x00\x00\x0b\x00\x08\x02_rels/.rels \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x92MO\xc30\x0c\x86\xefH\xfc\x87\xc8\xf7\xd5\xdd\x90\x10BKwAH\xbb!T~\x80I\xdc\x0f\xb5\x8d\xa3$\x1b\xdd\xbf\'\x1c\x10T\x1a\x83\x03G\x7f\xbd~\xfc\xca\xdb\xdd<\x8d\xea\xc8!\xf6\xe24\xac\x8b\x12\x14;#\xb6w\xad\x86\x97\xfaqu\x07*&r\x96Fq\xac\xe1\xc4\x11v\xd5\xf5\xd5\xf6\x99GJy(v\xbd\x8f*\xab\xb8\xa8\xa1K\xc9\xdf#F\xd3\xf1D\xb1\x10\xcf.W\x1a\t\x13\xa5\x1c\x86\x16=\x99\x81Z\xc6MY\xdeb\xf8\xae\x01\xd5BS\xed\xad\x86\xb0\xb77\xa0\xea\x93\xcf\x9b\x7f\xd7\x96\xa6\xe9\r?\x889L\xec\xd2\x99\x15\xc8sbg\xd9\xae|\xc8l!\xf5\xf9\x1aUSh9i\xb0b\x9er:"y_dl\xc0\xf3D\x9b\xbf\x13\xfd|-N\x9c\xc8R"4\x12\xf82\xcfG\xc7%\xa0\xf5\x7fZ\xb44\xf1\xcb\x9dy\xc47\t\xc3\xab\xc8\xf0\xc9\x82\x8b\x1f\xa8\xde\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x04\x9f\xdf\xe7e\x03\x00\x00_\x08\x00\x00\x0f\x00\x00\x00xl/workbook.xml\xacU\xefO\xdb<\x10\xfe>i\xffC\x94\xef&v~\'\xa2LM\x93jHP!(\xa0WB\x9aL\xe2\x12\x8b$\xee\x1c\x87\x16\xa1\xfd\xef;\xa7M\x81\xf5\xd5\xd4\xb1U\xad\x1d\xfb\x9c\xc7\xcf\xdd=w=\xfe\xb2\xae+\xe3\x89\xc9\x96\x8bfd\x92#l\x1a\xac\xc9E\xc1\x9b\x87\x91y=\x9f\xa2\xd04ZE\x9b\x82V\xa2a#\xf3\x99\xb5\xe6\x97\x93\xcf\x9f\x8eWB>\xde\x0b\xf1h\x00@\xd3\x8e\xccR\xa9elYm^\xb2\x9a\xb6Gb\xc9\x1a\xb0,\x84\xac\xa9\x82\xa5|\xb0\xda\xa5d\xb4hK\xc6T]Y6\xc6\xbeUS\xde\x98\x1b\x84X\x1e\x82!\x16\x0b\x9e\xb3T\xe4]\xcd\x1a\xb5\x01\x91\xac\xa2\n\xe8\xb7%_\xb6\x03Z\x9d\x1f\x02WS\xf9\xd8-Q.\xea%@\xdc\xf3\x8a\xab\xe7\x1e\xd44\xea<>}h\x84\xa4\xf7\x15\xb8\xbd&\x9e\xb1\x96\xf0\xf5\xe1G0\x0c\xf6p\x13\x98\xf6\xae\xaay.E+\x16\xea\x08\xa0\xad\r\xe9=\xff\t\xb6\x08y\x17\x82\xf5~\x0c\x0eCr-\xc9\x9e\xb8\xce\xe1\x8e\x95\xf4?\xc8\xca\xdfa\xf9\xaf`\x04\xff5\x1a\x01i\xf5Z\x89!x\x1fD\xf3v\xdcl\xf3\xe4x\xc1+v\xb3\x91\xaeA\x97\xcb\x19\xadu\xa6*\xd3\xa8h\xab\xb2\x82+V\x8c\xcc\x00\x96b\xc5\xdem\xc8n\x99t\xbc\x02\xab\x1d\xf9vhZ\';9_H\xa3`\x0b\xdaUj\x0eB\x1e\xe0\xa12|?\xb2=}\x12\x841\xae\x14\x93\rUl"\x1a\x05:\xdc\xfa\xf5\xb7\x9a\xeb\xb1\'\xa5\x00\x85\x1b\x97\xec{\xc7%\x83\xc2\x02}\x81\xaf0\xd2<\xa6\xf7\xed\x05U\xa5\xd1\xc9jdN\xe2\xbb\xeb\x16\xdc\xbf\x9b\x8d\xff\x1b\xcf\xb2Y\xfa\xf5\xfan\xa8\x8c\xf6\xee\x8d<\xe9~-\xfc\x81@i\xae\xbd\xb6\xc0\xed\r\xb5\xcd\xf3\xaf!\x00\x862\x1eDx\xa1\xa4\x01\xcf\xa7\xe9\x19$\xe2\x8a>AZ \xf9\xc5\xb6jO!\xee\xe1\xb7\x97l\x12dc\x0f\x13\x94\x06$En\x82}\x14fI\x86\xbc\x89\xef`\xcfq\xecq\x10\xfd\x00/\xa4\x1f\xe7\x82v\xaa\xdc\xa6Zc\x8eL\x17\xf2\xbag:\xa7\xeb\xc1Bp\xdc\xf1\xe2\xf5\xfe\x17\xbc\xfd =\xff2\x0c\xb6\x1f\xdaS\xdd\xd4n8[\xb5\xaf\xa2\xd0Kc}\xcb\x9bB\xacF&"\x18\x9a\xe2\xf3\xfb\xe5\xaa7\xde\xf2B\x95\xa0*\xc7\xf6\xa0x6{_\x19\x7f(\x811\xb1]\xbd\t\xe2\xd7\xccF\xe6K\x86I\xe0\xfb$B\x81O\x08r\xa3,@\xc9\xc4vP\xe4\xf9\xbe\xe7\xd9n\x18\xa4\xb8gd\xbd\xa1\xd4\xb7O\xa0\xd6\xcfF\xd3K\xfeJ\xb7T\x02}Z\xcf:\xba\xf0,c}\x87<-H\x9f\xbd\xe1\xb5\x9cV9H\\O\xfd\xc1\x88`;\xd2\'\xd8Z\x9d\xb5\xaa\x9fA]\x1c\xe8\x11\x17\x8f\x03\x1c\xb9\x08g\x8e\x87\xdc0\xb2Q\xe8:6\x9a\xb8\xa9\x9dyA\x96f\x89\xa7\xf3\xa3\xdb\x7f\xfc/\x9a`/\xf2x\xf8_\xd1,K*\xd5\\\xd2\xfc\x11\xfe\x8d.\xd9"\xa1-(i\xe3\x10\xf0}K6\xf1\xc2\x04;@\xd1\x9d\x92)rI\x84Q\x92\xf8.\xf2\xd2\xa9\xe3\x81\xbe&\x997}%\xab\xdd_|\xb0\x05\x85V\xff6\xa3\xaa\x83\xf2\xd4\x95\xd9\xafc=N\xb7\xbb\xbb\xcd\xc5fc\x9b\xa7wE\x17_\xa6:\xee\xdb\xb7\x7fw\xf0\n\xbc\xaf\xd8\x81\x87\xa77\x07\x1e\x9c\xcc\xce\xe7\xe7\x07\x9e=\xcb\xe6\xdfn\xa7\xbd\x90\xfe\xd7[\xab\xcf\x86\x1e{\rYC\x0eO~\x02\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x81>\x94\x97\xf3\x00\x00\x00\xba\x02\x00\x00\x1a\x00\x08\x01xl/_rels/workbook.xml.rels \xa2\x04\x01(\xa0\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xacRMK\xc40\x10\xbd\x0b\xfe\x870w\x9bv\x15\x11\xd9t/"\xecU\xeb\x0f\x08\xc9\xb4)\xdb&!3~\xf4\xdf\x1b*\xba]X\xd6K/\x03o\x86y\xef\xcd\xc7v\xf75\x0e\xe2\x03\x13\xf5\xc1+\xa8\x8a\x12\x04z\x13l\xef;\x05o\xcd\xf3\xcd\x03\x08b\xed\xad\x1e\x82G\x05\x13\x12\xec\xea\xeb\xab\xed\x0b\x0e\x9as\x13\xb9>\x92\xc8,\x9e\x148\xe6\xf8(%\x19\x87\xa3\xa6"D\xf4\xb9\xd2\x864j\xce0u2js\xd0\x1d\xcaMY\xde\xcb\xb4\xe4\x80\xfa\x84S\xec\xad\x82\xb4\xb7\xb7 \x9a)f\xe5\xff\xb9C\xdb\xf6\x06\x9f\x82y\x1f\xd1\xf3\x19\tI<\ry\x00\xd1\xe8\xd4!+\xf8\xc1E\xf6\x08\xf2\xbc\xfcfMy\xcek\xc1\xa3\xfa\x0c\xe5\x1c\xabK\x1e\xaa5=|\x86t \x87\xc8G\x1f\x7f)\x92s\xe5\xa2\x99\xbbU\xef\xe1tB\xfb\xca)\xbf\xdb\xf2,\xcb\xf4\xeff\xe4\xc9\xc7\xd5\xdf\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00~\xb4\xc1\xd6\xf9\x03\x00\x00\x1d\x0f\x00\x00\x18\x00\x00\x00xl/worksheets/sheet1.xml\x9cW]o\xe28\x14}\x1fi\xffC\x94w\xc8wH\x100\x9a\xf09\x0f+\xadvw\xe6\xdd\x04\x03Q\x938\x9b\xb8\xb4\xd5h\xfe\xfb^\'\r1\xd7\xa6j[Q)p\x8e\xef\xbd>>\xf7bf_\x9f\x8b\xdc\xb8\xd0\xba\xc9X97\x9d\xb1m\x1a\xb4L\xd9!+Os\xf3\xc7\xbf\x9bQd\x1a\r\'\xe5\x81\xe4\xac\xa4s\xf3\x856\xe6\xd7\xc5\x1f_fO\xac~h\xce\x94r\x03"\x94\xcd\xdc<s^M-\xabI\xcf\xb4 \xcd\x98U\xb4\x04\xe4\xc8\xea\x82px[\x9f\xac\xa6\xaa)9\xb4\x8b\x8a\xdcrm;\xb4\n\x92\x95f\x17aZ\xbf\'\x06;\x1e\xb3\x94\xaeX\xfaX\xd0\x92wAj\x9a\x13\x0e\xf57\xe7\xacj\xfahE\xfa\x9ep\x05\xa9\x1f\x1e\xabQ\xca\x8a\nB\xec\xb3<\xe3/mP\xd3(\xd2\xe9\xf7S\xc9j\xb2\xcfa\xdf\xcf\x8eOR\xe3\xb9\x86\x97\x0b\xff^\x9f\xa6\xfd\\\xc9Tdi\xcd\x1av\xe4c\x88lu5\xab\xdb\x8f\xad\xd8"\xe95\x92\xba\xffw\x85q|\xab\xa6\x97L\x1c\xe0\x10\xca\xfd\\INp\x8d\xe5\x0e\xc1\xbcO\x06\x0b\xaf\xc1\x84\\\xf5\xf41;\xcc\xcd_\xeb\xf5&\xdeL\x1c{\xb4\t\xc2\xc9\xc8\xf7V\xee(\x0e\x82\xc9\xc8u#\xdf\x0b\xed(N"\xfb\xb7\xb9\x98\x1d28a\xb1+\xa3\xa6\xc7\xb9\xf9\xcd\x99\xeeb\xd3Z\xccZ\xff\xfc\xcc\xe8S#=\x1b\x9c\xec\xff\xa19M9\x85\x1c\x8ei\x08{\xee\x19{\x10\xc4\xef\xf0\x91\r\x11\x9b\x96 "\x92\x94g\x17\xba\xa4y>7wP\\\xf3_\x9b\x03\x1e!\x81u\xcd ?\xf7\xd96\xad\xa1\xff\xaa\x8d\x03=\x92\xc7\x9c\xff\xcd\x9ev4;\x9d9\xa4\xf5\xc7>lT8ezxY\xd1&\x05\x8bB\xeaq\x1b\xb6\x8d\xba"\x9c,f5{2\xe0\xb4\xa1\xcc\xa6"\xa2w\x9c)\xb4\x99\x08\xe1Fcx\xd2\x86X\xccR\xb1\xe8\x9bX\xd5\xae\x05z\x03\xbb\xba,\xec\x99u\x81R\xd3WF\xa22\x9c[\xc6Re\xb8\xb7\x8c\x95\xca\xf0n\x19k\x95\xe1\xdf26*#\xb8elUFx\xcb\xd8\xa9\x8c\xc9\x95a\x81\x8eW1\xc1\xaf\xb2\x98oJ(\xb8\xa0u+\x9ec#q\x92\x1e5\xae\x02GH>\x95\x11#\xf9\xe4\x0c\x1e:\x9f\xb5\x0c\x066\xfc!\xdd:\xdck\xcb\xf3\xbd\xc8\xc7\xaa\xa9\xe9\x1d\x14b\xa7\xa1\x0c\xdb\xbc\xd1M\xb8\xff\xe3&\x14\xab\x06\x05\x91y\x92\x1e\x1d\x14t\x10e\xa9\xa1 \x83\xad\xe4\x1c.:\x82\xb5\x0c\x86BD\xa4a\x87\xf7\x1a\x06\xfe\xe0\x9a\xb6\x8b\xb6\x9a\xfc\xc8\xbe\xed\\\x10{\x94v1\x9c\xc4\x8d\x86\xd0\xf5\xef\xf6\x9e\xe0\x0e\xca\xa1=\'=*\xe5D\x1d\xb1\xd4P\xd0\xe6Vr\x0e\x0f)\xbf\x96\xc1\x89\xc6}\x1d\xfe\xaa\x9c\xef\xdbX9M~t8;\r\xe5\x8er\xc1\x07\x94\x13\xdcA9tZI\x8fJ\xca\xa1\xa6\\j(\xd8sr\x0e\x17)\xbf\x96\xc1\x10\xae/\xd8s\x1d\xde+\x17\xc6H\x96\xad&?\xee[\r\xe5N\xdf\x86\x1fPNp\x07\xe5\xd08IztP\xceEe-U\n\x1exr\n<\xb0\xd62\x18i,\xd7\xe1}\xb3\xfa6\x12~\xab\xa9\x10\r\xed\x9dJq\xeeXn\xf2\xa9\x81\'V\r\x12\xa2\x02\x93\x1e\x95$\xc4\x03OC\xc1\xe6\x93s\xb8H\xe0\xb5\x0c\x06\x9a\x81\xd7\xe1\xbd\xf9\xec\x08k\xa8\xe6wp\xdbj(w\xcc\'~\x14H_\x1ao~\xd9\n\xee\xa0\x1c\x9a&I\x8fJ\xca\xa1\xce^\xaa\x14\x07\x0f<9\x87\x87\x95\x93\xc1\x89\xa6m;\xfcU97\x0e\xd1\xfa\xad\xa6D\xec>M\x89w\xdc\x17\x7f\xca}b\xd5\xa0!:\xb7\xa4G%\rQ\x8f/5\x14\xec>9\x87\x87/{2\x18x\xea\xe8\xeb\xf0\xde}\x81\x87\x04\xda\xaa\xf9\x1d\xfcu\xab\xa1`\xf7u7\xf3\xee\x0e]\x91\x13\xfd\x93\xd4\xa7\xacl\x8c\x9c\x1e\xdb{6\x18\xb8\xee\xae\xe2\xf6\x18\x9e9\xab\xc4\xed{\x02Cu\xcf8gE\xff\xee\x0c?C)\xdc\xa5\xc5\xcd\xdc82\xc6\xfb7\xe2\xf6\x7f\xfda\xbb\xf8\x1f\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xc1\x17\x10\xbeN\x07\x00\x00\xc6 \x00\x00\x13\x00\x00\x00xl/theme/theme1.xml\xecY\xcd\x8b\x1b7\x14\xbf\x17\xfa?\x0csw\xfc5\xe3\x8f%\xde\xe0\xcfl\x93\xdd$d\x9d\x94\x1c\xb5\xb6\xecQV32\x92\xbc\x1b\x13\x02%9\xf5R(\xa4\xa5\x97Bo=\x94\xd2@\x03\r\xbd\xf4\x8f\t$\xb4\xe9\x1f\xd1\'\xcd\xd8#\xad\xe5$\x9blJZv\r\x8bG\xfe\xbd\xa7\xa7\xf7\x9e~z\xf3t\xf1\xd2\xbd\x98zG\x98\x0b\xc2\x92\x96_\xbeP\xf2=\x9c\x8c\xd8\x98$\xd3\x96\x7fk8(4|OH\x94\x8c\x11e\tn\xf9\x0b,\xfcK\xdb\x9f~r\x11m\xc9\x08\xc7\xd8\x03\xf9Dl\xa1\x96\x1fI9\xdb*\x16\xc5\x08\x86\x91\xb8\xc0f8\x81\xdf&\x8c\xc7H\xc2#\x9f\x16\xc7\x1c\x1d\x83\xde\x98\x16+\xa5R\xad\x18#\x92\xf8^\x82bP{}2!#\xec\r\x95J\x7f{\xa9\xbcO\xe11\x91B\r\x8c(\xdfW\xaa\xb1%\xa1\xb1\xe3\xc3\xb2B\x88\x85\xe8R\xee\x1d!\xda\xf2a\x9e1;\x1e\xe2{\xd2\xf7(\x12\x12~h\xf9%\xfd\xe7\x17\xb7/\x16\xd1V&D\xe5\x06YCn\xa0\xff2\xb9L`|X\xd1s\xf2\xe9\xc1j\xd2 \x08\x83Z{\xa5_\x03\xa8\\\xc7\xf5\xeb\xfdZ\xbf\xb6\xd2\xa7\x01h4\x82\x95\xa6\xb6\xd8:\xeb\x95n\x90a\rP\xfa\xd5\xa1\xbbW\xefU\xcb\x16\xde\xd0_]\xb3\xb9\x1d\xaa\x8f\x85\xd7\xa0T\x7f\xb0\x86\x1f\x0c\xba\xe0E\x0b\xafA)>\\\xc3\x87\x9df\xa7g\xeb\xd7\xa0\x14_[\xc3\xd7K\xed^P\xb7\xf4kPDIr\xb8\x86.\x85\xb5jw\xb9\xda\x15d\xc2\xe8\x8e\x13\xde\x0c\x83A\xbd\x92)\xcfQ\x90\r\xab\xecRSLX"7\xe5Z\x8c\xee2>\x00\x80\x02R$I\xe2\xc9\xc5\x0cO\xd0\x08\xb2\xb8\x8b(9\xe0\xc4\xdb%\xd3\x08\x12o\x86\x12&`\xb8T)\rJU\xf8\xaf>\x81\xfe\xa6#\x8a\xb602\xa4\x95]`\x89X\x1bR\xf6xb\xc4\xc9L\xb6\xfc+\xa0\xd57 /\x9e={\xfe\xf0\xe9\xf3\x87\xbf=\x7f\xf4\xe8\xf9\xc3_\xb2\xb9\xb5*Kn\x07%SS\xee\xd5\x8f_\xff\xfd\xfd\x17\xde_\xbf\xfe\xf0\xea\xf17\xe9\xd4\'\xf1\xc2\xc4\xbf\xfc\xf9\xcb\x97\xbf\xff\xf1:\xf5\xb0\xe2\xdc\x15/\xbe}\xf2\xf2\xe9\x93\x17\xdf}\xf5\xe7O\x8f\x1d\xda\xdb\x1c\x1d\x98\xf0!\x89\xb1\xf0\xae\xe1c\xef&\x8ba\x81\x0e\xfb\xf1\x01?\x9d\xc40B\xc4\x92@\x11\xe8v\xa8\xee\xcb\xc8\x02^[ \xea\xc2u\xb0\xed\xc2\xdb\x1cX\xc6\x05\xbc<\xbfk\xd9\xba\x1f\xf1\xb9$\x8e\x99\xafF\xb1\x05\xdcc\x8cv\x18w:\xe0\xaa\x9a\xcb\xf0\xf0p\x9eL\xdd\x93\xf3\xb9\x89\xbb\x89\xd0\x91k\xee.J\xac\x00\xf7\xe73\xa0W\xe2R\xd9\x8d\xb0e\xe6\r\x8a\x12\x89\xa68\xc1\xd2S\xbf\xb1C\x8c\x1d\xab\xbbC\x88\xe5\xd7=2\xe2L\xb0\x89\xf4\xee\x10\xaf\x83\x88\xd3%Cr`%R.\xb4Cb\x88\xcb\xc2e \x84\xda\xf2\xcd\xdem\xaf\xc3\xa8k\xd5=|d#a[ \xea0~\x88\xa9\xe5\xc6\xcbh.Q\xecR9D15\x1d\xbe\x8bd\xe42r\x7f\xc1G&\xae/$Dz\x8a)\xf3\xfac,\x84K\xe6:\x87\xf5\x1aA\xbf\n\x0c\xe3\x0e\xfb\x1e]\xc46\x92Kr\xe8\xd2\xb9\x8b\x183\x91=v\xd8\x8dP<s\xdaL\x92\xc8\xc4~&\x0e!E\x91w\x83I\x17|\x8f\xd9;D=C\x1cP\xb21\xdc\xb7\t\xb6\xc2\xfdf"\xb8\x05\xe4j\x9a\x94\'\x88\xfae\xce\x1d\xb1\xbc\x8c\x99\xbd\x1f\x17t\x82\xb0\x8be\xda<\xb6\xd8\xb5\xcd\x893;:\xf3\xa9\x95\xda\xbb\x18St\x8c\xc6\x18{\xb7>sX\xd0a3\xcb\xe7\xb9\xd1W"`\x95\x1d\xecJ\xac+\xc8\xceU\xf5\x9c`\x01e\x92\xaak\xd6)r\x97\x08+e\xf7\xf1\x94m\xb0goq\x82x\x16(\x89\x11\xdf\xa4\xf9\x1aD\xddJ]8\xe5\x9cTz\x9d\x8e\x0eM\xe05\x02\xe5\x1f\xe4\x8b\xd3)\xd7\x05\xe80\x92\xbb\xbfI\xeb\x8d\x08Yg\x97z\x16\xee|]p+~o\xb3\xc7`_\xde=\xed\xbe\x04\x19|j\x19 \xf6\xb7\xf6\xcd\x10Qk\x82<a\x86\x08\n\x0c\x17\xdd\x82\x88\x15\xfe\\D\x9d\xabZl\xee\x94\x9b\xd8\x9b6\x0f\x03\x14FV\xbd\x13\x93\xe4\x8d\xc5\xcf\x89\xb2\'\xfcw\xca\x1ew\x01s\x06\x05\x8f[\xf1\xfb\x94:\x9b(e\xe7D\x81\xb3\t\xf7\x1f,kzh\x9e\xdc\xc0p\x92\xacs\xd6yUs^\xd5\xf8\xff\xfb\xaaf\xd3^>\xafe\xcek\x99\xf3Z\xc6\xf5\xf6\xf5Aj\x99\xbc|\x81\xca&\xef\xf2\xe8\x9eO\xbc\xb1\xe53!\x94\xee\xcb\x05\xc5\xbbBw}\x04\xbc\xd1\x8c\x070\xa8\xdbQ\xba\'\xb9j\x01\xce"\xf8\x9a5\x98,\xdc\x94#-\xe3q&?\'2\xda\x8f\xd0\x0cZCe\xdd\xc0\x9c\x8aL\xf5Tx3&\xa0c\xa4\x87u+\x15\x9f\xd0\xad\xfbN\xf3x\x8f\x8d\xd3Ng\xb9\xac\xba\x9a\xa9\x0b\x05\x92\xf9x)\\\x8dC\x97J\xa6\xe8Z=\xef\xde\xad\xd4\xeb~\xe8TwY\x97\x06(\xd9\xd3\x18aLf\x1bQu\x18Q_\x0eB\x14^g\x84^\xd9\x99X\xd1tX\xd1P\xea\x97\xa1ZFq\xe5\n0m\x15\x15x\xe5\xf6\xe0E\xbd\xe5\x87A\xdaA\x86f\x1c\x94\xe7c\x15\xa7\xb4\x99\xbc\x8c\xae\n\xce\x99Fz\x933\xa9\x99\x01Pb/3 \x8ftS\xd9\xbaqyjui\xaa\xbdE\xa4-#\x8ct\xb3\x8d0\xd20\x82\x17\xe1,;\xcd\x96\xfbY\xc6\xba\x99\x87\xd42O\xb9b\xb9\x1br3\xea\x8d\x0f\x11kE"\'\xb8\x81&&S\xd0\xc4;n\xf9\xb5j\x08\xb7*#4k\xf9\x13\xe8\x18\xc3\xd7x\x06\xb9#\xd4[\x17\xa2S\xb8v\x19I\x9en\xf8wa\x96\x19\x17\xb2\x87D\x94:\\\x93N\xca\x061\x91\x98{\x94\xc4-_-\x7f\x95\r4\xd1\x1c\xa2m+W\x80\x10>Z\xe3\x9a@+\x1f\x9bq\x10t;\xc8x2\xc1#i\x86\xdd\x18Q\x9eN\x1f\x81\xe1S\xaep\xfe\xaa\xc5\xdf\x1d\xac$\xd9\x1c\xc2\xbd\x1f\x8d\x8f\xbd\x03:\xe77\x11\xa4XX/+\x07\x8e\x89\x80\x8b\x83r\xea\xcd1\x81\x9b\xb0\x15\x91\xe5\xf9w\xe2`\xcah\xd7\xbc\x8a\xd29\x94\x8e#:\x8bPv\xa2\x98d\x9e\xc25\x89\xae\xcc\xd1O+\x1f\x18O\xd9\x9a\xc1\xa1\xeb.<\x98\xaa\x03\xf6\xbdO\xdd7\x1f\xd5\xcas\x06i\xe6g\xa6\xc5*\xea\xd4t\x93\xe9\x87;\xe4\r\xab\xf2C\xd4\xb2*\xa5n\xfdN-r\xaek.\xb9\x0e\x12\xd5yJ\xbc\xe1\xd4}\x8b\x03\xc10-\x9f\xcc2MY\xbcN\xc3\x8a\xb3\xb3Q\xdb\xb43,\x08\x0cO\xd46\xf8muF8=\xf1\xae\'?\xc8\x9d\xccZu@,\xebJ\x9d\xf8\xfa\xca\xdc\xbc\xd5f\x07w\x81<zp\x7f8\xa7R\xe8PBo\x97#(\xfa\xd2\x1b\xc8\x946`\x8b\xdc\x93Y\x8d\x08\xdf\xbc9\'-\xff~)l\x07\xddJ\xd8-\x94\x1aa\xbf\x10T\x83R\xa1\x11\xb6\xab\x85v\x18V\xcb\xfd\xb0\\\xeau*\x0f\xe0`\x91Q\\\x0e\xd3\xeb\xfa\x01\\a\xd0Evi\xaf\xc7\xd7.\xee\xe3\xe5-\xcd\x85\x11\x8b\x8bL_\xcc\x17\xb5\xe1\xfa\xe2\xbe\\\xd9|q\xef\x11 \x9d\xfb\xb5\xca\xa0Ymvj\x85f\xb5=(\x04\xbdN\xa3\xd0\xec\xd6:\x85^\xad[\xef\rz\xdd\xb0\xd1\x1c<\xf0\xbd#\r\x0e\xda\xd5nP\xeb7\n\xb5r\xb7[\x08j%e~\xa3Y\xa8\x07\x95J;\xa8\xb7\x1b\xfd\xa0\xfd +c`\xe5)}d\xbe\x00\xf7j\xbb\xb6\xff\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xc27!*\x15\x03\x00\x00w\x08\x00\x00\r\x00\x00\x00xl/styles.xml\xb4V]o\x9b0\x14}\x9f\xb4\xff`\xf9\x9d\xf2Q\xc8\x92\x08\xa8\x9a\xa6H\x95\xb6jR3i\xaf\x0e\x98\xc4\xaa?\x90qZ\xd2i\xff}\xd7@\x12\xbavk\x96j/\xc1\xbe\xb6\xcf=\xf7\xde\xe3\xeb\xc4\x17\x8d\xe0\xe8\x81\xea\x9a)\x99`\xff\xcc\xc3\x88\xca\\\x15L\xae\x12\xfcm\x919c\x8cjCdA\xb8\x924\xc1[Z\xe3\x8b\xf4\xe3\x87\xb86[N\xef\xd6\x94\x1a\x04\x10\xb2N\xf0\xda\x98j\xea\xbau\xbe\xa6\x82\xd4g\xaa\xa2\x12VJ\xa5\x0510\xd5+\xb7\xae4%Em\x0f\t\xee\x06\x9e7r\x05a\x12w\x08S\x91\x1f\x03"\x88\xbe\xdfTN\xaeDE\x0c[2\xce\xcc\xb6\xc5\xc2H\xe4\xd3\x9b\x95T\x9a,9Pm\xfc\x90\xe4\xa8\xf1G:@\x8d\xde9i\xad/\xfc\x08\x96kU\xab\xd2\x9c\x01\xae\xab\xca\x92\xe5\xf4%\xdd\x89;qI~@\x02\xe4\xd3\x90\xfc\xc8\xf5\x82g\xb17\xfaD\xa4\xd0\xd5\xf4\x81\xd9\xf2\xe14.\x9545\xca\xd5F\x9a\x04\x07@\xd4\xa6`z/\xd5\xa3\xcc\

In [2]:
import pandas as pd

df= pd.read_excel("pandas_new.xlsx")
df.head()

   EmpID     Name Department  Age  Salary   JoinDate       City Gender
0    101    Alice         HR   30   50000 2020-01-15   New York      F
1    102      Bob         IT   28   65000 2019-03-23  San Diego      M
2    103  Charlie    Finance   32   70000 2021-07-30    Chicago      M
3    104    Diana         IT   26   62000 2022-05-17   New York      F
4    105    Ethan         HR   45   80000 2018-11-02     Boston      M

In [3]:
df.columns
df.dtypes

EmpID                  int64
Name                  object
Department            object
Age                    int64
Salary                 int64
JoinDate      datetime64[ns]
City                  object
Gender                object
dtype: object

In [4]:
df.shape

(8, 8)

In [5]:
df.isnull().sum()

EmpID         0
Name          0
Department    0
Age           0
Salary        0
JoinDate      0
City          0
Gender        0
dtype: int64

In [6]:
df[df['Department'] == 'IT']

   EmpID   Name Department  Age  Salary   JoinDate       City Gender
1    102    Bob         IT   28   65000 2019-03-23  San Diego      M
3    104  Diana         IT   26   62000 2022-05-17   New York      F

In [7]:
df[df['Age']>30]

   EmpID     Name Department  Age  Salary   JoinDate       City Gender
2    103  Charlie    Finance   32   70000 2021-07-30    Chicago      M
4    105    Ethan         HR   45   80000 2018-11-02     Boston      M
6    107   George    Finance   39   72000 2017-08-22     Boston      M
7    108   Hannah  Marketing   33   53000 2021-12-01  San Diego      F

In [8]:
df['JoinDate']=pd.to_datetime(df['JoinDate'])
df[df['JoinDate'].dt.year > 2020]

   EmpID     Name Department  Age  Salary   JoinDate       City Gender
2    103  Charlie    Finance   32   70000 2021-07-30    Chicago      M
3    104    Diana         IT   26   62000 2022-05-17   New York      F
7    108   Hannah  Marketing   33   53000 2021-12-01  San Diego      F

In [9]:
df[df['City'].isin(['New York','Chicago'])]

   EmpID     Name Department  Age  Salary   JoinDate      City Gender
0    101    Alice         HR   30   50000 2020-01-15  New York      F
2    103  Charlie    Finance   32   70000 2021-07-30   Chicago      M
3    104    Diana         IT   26   62000 2022-05-17  New York      F
5    106    Fiona  Marketing   29   55000 2020-09-12   Chicago      F

In [10]:
df['Salary'].mean()

np.float64(63375.0)

In [12]:
df.groupby('Department')['Salary'].max()

Department
Finance      72000
HR           80000
IT           65000
Marketing    55000
Name: Salary, dtype: int64

In [13]:
df['City'].value_counts()

City
New York     2
San Diego    2
Chicago      2
Boston       2
Name: count, dtype: int64

In [16]:
df[df['Gender'] == 'F']['Age'].mean()

np.float64(29.5)

In [17]:
df.sort_values(by='Salary',ascending=False)

   EmpID     Name Department  Age  Salary   JoinDate       City Gender
4    105    Ethan         HR   45   80000 2018-11-02     Boston      M
6    107   George    Finance   39   72000 2017-08-22     Boston      M
2    103  Charlie    Finance   32   70000 2021-07-30    Chicago      M
1    102      Bob         IT   28   65000 2019-03-23  San Diego      M
3    104    Diana         IT   26   62000 2022-05-17   New York      F
5    106    Fiona  Marketing   29   55000 2020-09-12    Chicago      F
7    108   Hannah  Marketing   33   53000 2021-12-01  San Diego      F
0    101    Alice         HR   30   50000 2020-01-15   New York      F

In [18]:
df.sort_values('Department')[['Salary','Age']].mean()

Salary    63375.00
Age          32.75
dtype: float64

In [20]:
df.sort_values(by=['Department','Age'],ascending=[True,True])

   EmpID     Name Department  Age  Salary   JoinDate       City Gender
2    103  Charlie    Finance   32   70000 2021-07-30    Chicago      M
6    107   George    Finance   39   72000 2017-08-22     Boston      M
0    101    Alice         HR   30   50000 2020-01-15   New York      F
4    105    Ethan         HR   45   80000 2018-11-02     Boston      M
3    104    Diana         IT   26   62000 2022-05-17   New York      F
1    102      Bob         IT   28   65000 2019-03-23  San Diego      M
5    106    Fiona  Marketing   29   55000 2020-09-12    Chicago      F
7    108   Hannah  Marketing   33   53000 2021-12-01  San Diego      F

In [22]:
df.loc[df.groupby('Department')['Age'].idxmin()]

   EmpID     Name Department  Age  Salary   JoinDate      City Gender
2    103  Charlie    Finance   32   70000 2021-07-30   Chicago      M
0    101    Alice         HR   30   50000 2020-01-15  New York      F
3    104    Diana         IT   26   62000 2022-05-17  New York      F
5    106    Fiona  Marketing   29   55000 2020-09-12   Chicago      F

In [24]:
from datetime import datetime
df['Year_Experience'] = (pd.Timestamp.now()- df['JoinDate']).dt.days // 365

In [25]:
print(df)

   EmpID     Name Department  Age  Salary   JoinDate       City Gender  \
0    101    Alice         HR   30   50000 2020-01-15   New York      F
1    102      Bob         IT   28   65000 2019-03-23  San Diego      M
2    103  Charlie    Finance   32   70000 2021-07-30    Chicago      M
3    104    Diana         IT   26   62000 2022-05-17   New York      F
4    105    Ethan         HR   45   80000 2018-11-02     Boston      M
5    106    Fiona  Marketing   29   55000 2020-09-12    Chicago      F
6    107   George    Finance   39   72000 2017-08-22     Boston      M
7    108   Hannah  Marketing   33   53000 2021-12-01  San Diego      F

   Year_Experience
0                6
1                6
2                4
3                3
4                7
5                5
6                8
7                4

In [26]:
df.loc[df['JoinDate'].idxmax()]

EmpID                              104
Name                             Diana
Department                          IT
Age                                 26
Salary                           62000
JoinDate           2022-05-17 00:00:00
City                          New York
Gender                               F
Year_Experience                      3
Name: 3, dtype: object

In [27]:
df['Salary_in_Lakhs'] = df['Salary']/100000

In [28]:
def seniority(age):
    if age < 30:
        return 'Junior'
    elif 30 <= age <= 40:
        return 'Mid'
    else:
        return 'Senior'

df['Seniority'] = df['Age'].apply(seniority)